### ISSUE TITLE
Add OpenCV+Contrib

### ISSUE THREAD

**Issue by ibaiGorordo** [iwatake2222/InferenceHelper_Binary#9]
Hi,

Thank you for this repository, it already saved me lot of time trying to build TFLite. 

Would it be possible to also add support for OpenCV with the Contrib modules? Particularly for Android, there are multiple guides on how to do it, but it is still quite a challenge. 

Thanks!

**Comment by iwatake2222** [comment]
Thank you for your opinion!
It will be useful. However, I'm sorry but I won't do it in this repository due to the following reasons:
- This repository is for libraries used in my InferenceHelper project. So, OpenCV + Contrib is out of scope
- I rarely use OpenCV + contrib, and it will be hard for me to build and maintain it

**Comment by ibaiGorordo** [comment]
No problem, I understand. I had to try :sweat_smile:

Still, thank you for this repository.
